config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    # Your stuff: custom urls includes go here
    url(r'^', include('presentation.urls', namespace='presentation')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('warp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

warp/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

warp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_profile_image_url(self):
        social_image = None
        if self.socialaccount_set.all():
            social_image = self.socialaccount_set.all()[0].get_avatar_url()
        if social_image:
            return social_image
        return '/static/images/default_profile.svg'

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

warp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from presentation.models import Presentation
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        if username == self.request.user.username:
            context['presentations'] = Presentation.objects.authored_by(username).order_by('-pk')[:9]
        else:
            context['presentations'] = Presentation.objects.authored_by(username).public().order_by('-pk')[:9]

        # TODO implement like presentation
        # context['like_presentation_list'] =

        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

warp/templates/users/user_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div id="user-profile">
  <div class="profile">
    <div class="container">
      <div class="row">
        <div class=" small-4 medium-3 columns text-right">
          <img class="user-profile-img" src="{{ object.get_profile_image_url }}" alt=""/>
        </div>
        <div class="small-8 medium-9 columns text-left">
          <h1 class="">{{ object.username }}</h1>
          {% if object.name %}
            <p>{{ object.name }}</p>
          {% endif %}
          {% if object.get_full_name %}
            <p>
              {{ object.get_full_name }}
            </p>
          {% endif %}
          {% if object.email %}
            <p>{{ object.email }}</p>
          {% endif %}

          {% if object == request.user %}
            <!-- Action buttons -->
            <p>
              <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Update My Info</a>
              <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
              <!-- Your Stuff: Custom user template urls -->
            </p>
            <!-- End Action buttons -->
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <hr>
  <!-- Presentation List  -->
  {% include "presentation/_list.html" %}

<!-- End Presentation List -->
{% endblock content %}
{% block extra_css %}
{% endblock %}

{% block extra_javascript %}
  <script src="{% static 'vendor/marked/marked.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/resize-slides.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/mdElemsToHtmlElems.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/list/index.min.js' %}"></script>
{% endblock %}

warp/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

warp/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}