config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    # Your stuff: custom urls includes go here
    url(r'^', include('presentation.urls', namespace='presentation')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('warp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

presentation/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.PresentationList.as_view(),
        name='list'
    ),
    url(
        regex=r'^search$',
        view=views.PresentationSearchList.as_view(),
        name='search'
    ),
    url(
        regex=r'^create$',
        view=views.PresentationCreate.as_view(),
        name='create'
    ),
    url(
        regex=r'^markdown-usage$',
        view=views.presentation_markdown_usage,
        name='markdown-usage'
    ),
    url(
        regex=r'^detail/(?P<pk>\d+)$',
        view=views.PresentationDetail.as_view(),
        name='detail'
    ),
    url(
        regex=r'^update/(?P<pk>\d+)$',
        view=views.PresentationUpdate.as_view(),
        name='update'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)$',
        view=views.PresentationDelete.as_view(),
        name='delete'
    ),
    url(
        regex=r'^like/(?P<pk>\d+)$',
        view=views.like_presentation,
        name='like'
    ),
]

warp/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

presentation/models.py
from django.contrib.postgres.search import SearchVector, SearchQuery
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Manager
from django.db.models import QuerySet
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager

from warp.users.models import User


class PresentationQuerySet(QuerySet):
    def public(self):
        return self.filter(is_public=True)

    def authored_by(self, author):
        return self.filter(author__username=author)

    def search(self, query):
        return self.annotate(
            search=SearchVector('subject', 'tags__name', 'author__username', 'slide__markdown'))\
            .filter(search=SearchQuery(query))\
            .filter(is_public=True)\
            .distinct('id')\
            .select_related('author')


class PresentationManager(Manager):
    def get_queryset(self):
        return PresentationQuerySet(self.model, using=self._db).select_related('author')

    def public(self):
        return self.get_queryset().public()

    def authored_by(self, author):
        return self.get_queryset().authored_by(author)

    def search(self, query):
        return self.get_queryset().search(query)


class Presentation(TimeStampedModel):
    subject = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    is_public = models.BooleanField(default=True)
    tags = TaggableManager()

    like_users = models.ManyToManyField(User, related_name='like_users')

    def like_toggle(self, user):
        is_like = self.is_user_like_presentation(user)
        if is_like:
            self.like_users.remove(user)
        else:
            self.like_users.add(user)

        result_like = not is_like
        self.likes = self.like_users.count()
        self.save()
        return result_like

    def is_user_like_presentation(self, user):
        is_like = False
        try:
            self.like_users.get(id=user.id)
            is_like = True
        except User.DoesNotExist:
            pass
        return is_like

    objects = PresentationManager()

    def view(self):
        self.views += 1
        self.save()

    def __str__(self):
        return self.subject

    def get_absolute_url(self, *args, **kwargs):
        return reverse('presentation:detail', kwargs={'pk': self.pk})


class Slide(TimeStampedModel):
    presentation = models.ForeignKey(Presentation, on_delete=models.CASCADE)
    slide_order = models.PositiveSmallIntegerField()
    markdown = models.TextField()

    def __str__(self):
        return self.markdown

warp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_profile_image_url(self):
        social_image = None
        if self.socialaccount_set.all():
            social_image = self.socialaccount_set.all()[0].get_avatar_url()
        if social_image:
            return social_image
        return '/static/images/default_profile.svg'

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

presentation/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms import RadioSelect

from .models import Presentation, Slide


class PresentationBaseForm(forms.ModelForm):
    subject = forms.CharField(max_length=50)
    markdown = forms.CharField(widget=forms.HiddenInput(), required=True)
    is_public = forms.BooleanField(initial=True,
                                   required=False,
                                   widget=RadioSelect(choices=[
                                       (True, 'public'), (False, 'private')]))

    def clean_tags(self):
        tags = self.cleaned_data['tags']
        if len(tags) > 20:
            raise ValidationError("Too much tags")
        for tag in tags:
            if len(tag) > 16:
                raise ValidationError("Too long tag")

        return tags

    def add_slide_list(self, presentation):
        markdown = self.cleaned_data.get('markdown')
        slide_list = re.split("={5,}", markdown)
        Slide.objects.filter(presentation=presentation).delete()

        for order_num, slide in enumerate(slide_list):
            Slide.objects.create(
                presentation=presentation,
                slide_order=order_num,
                markdown=slide
            )

    @staticmethod
    class Meta:
        model = Presentation
        fields = ['subject', 'markdown', 'is_public', "tags"]


class PresentationCreateForm(PresentationBaseForm):
    def save(self, commit=True):
        instance = super(PresentationCreateForm, self).save(commit=False)
        instance.author = self.author
        instance.save()

        self.add_slide_list(instance)
        return instance


class PresentationUpdateForm(PresentationBaseForm):
    def save(self, commit=True):
        instance = super(PresentationUpdateForm, self).save(commit=False)
        instance.subject = self.cleaned_data.get('subject')
        instance.is_public = self.cleaned_data.get('is_public')
        instance.author = self.author
        instance.save()

        self.add_slide_list(instance)
        return instance

presentation/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponse
from django.http import HttpResponseNotAllowed

from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic import DeleteView
from django.views.generic import UpdateView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from pure_pagination import PaginationMixin

from warp.users.models import User

from .forms import PresentationCreateForm, PresentationUpdateForm
from .models import Presentation, Slide
from .behaviors import AuthorRequiredMixin


class PresentationList(PaginationMixin, ListView):
    model = Presentation
    paginate_by = 9
    context_object_name = 'presentations'
    ordering = ['-pk']

    def get_queryset(self):
        return super(PresentationList, self).get_queryset().public()


class PresentationSearchList(PaginationMixin, ListView):
    model = Presentation
    paginate_by = 9
    context_object_name = 'presentations'

    def get_queryset(self):
        query = self.request.GET['query']
        return super(PresentationSearchList, self).get_queryset().search(query)


class PresentationDetail(DetailView):
    model = Presentation
    context_object_name = 'presentation'

    def get_context_data(self, **kwargs):
        context = super(PresentationDetail, self).get_context_data()
        context['is_user_liked'] = self.get_object().is_user_like_presentation(self.request.user)
        self.object.view()
        return context


class PresentationCreate(LoginRequiredMixin, CreateView):
    model = Presentation
    form_class = PresentationCreateForm

    def get_context_data(self, **kwargs):
        context = super(PresentationCreate, self).get_context_data()
        context['action_url'] = reverse('presentation:create')
        context['submit_button_text'] = 'Create'
        return context

    def form_valid(self, form):
        form.author = self.request.user
        form.cleaned_data['author'] = User.objects.get(username=form.author.username)
        form.save()
        form.save_m2m()
        return super(PresentationCreate, self).form_valid(form)


class PresentationUpdate(AuthorRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Presentation
    form_class = PresentationUpdateForm

    def get_context_data(self, **kwargs):
        context = super(PresentationUpdate, self).get_context_data()
        context['action_url'] = reverse('presentation:update', kwargs={'pk': self.object.pk})
        context['submit_button_text'] = 'Update'
        slides = Slide.objects.filter(presentation=self.object.pk)
        markdowns = []
        for slide in slides:
            markdowns.append(slide.markdown)
        markdown = '====='.join(markdowns)
        context['markdown'] = markdown
        return context

    def form_valid(self, form):
        form.author = self.request.user
        form.save()
        form.save_m2m()
        return super(PresentationUpdate, self).form_valid(form)


class PresentationDelete(AuthorRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Presentation
    success_url = reverse_lazy("presentation:list")


@login_required
def like_presentation(request, pk):
    if request.method == 'PUT':
        presentation = Presentation.objects.get(pk=pk)
        is_like = presentation.like_toggle(request.user)
        return HttpResponse(status=200, content=is_like)

    return HttpResponseNotAllowed(["PUT"])


def presentation_markdown_usage(request):
    return render(request, 'presentation/markdown_usage.html')

warp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from presentation.models import Presentation
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        if username == self.request.user.username:
            context['presentations'] = Presentation.objects.authored_by(username).order_by('-pk')[:9]
        else:
            context['presentations'] = Presentation.objects.authored_by(username).public().order_by('-pk')[:9]

        # TODO implement like presentation
        # context['like_presentation_list'] =

        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

warp/templates/presentation/_list.html
<div class="presentation">
  <div class="row" data-equalizer data-equalize-on="medium" id="test-eq">
    {% for presentation in presentations %}
      <a href="{% url 'presentation:detail' pk=presentation.pk %}">
        <div class="medium-6 large-4 columns">
          <div class="preview">
            <div class="slide">{{ presentation.slide_set.first.markdown }}</div>
          </div>
          <div class="presentation-footer">
            <div class="warp-list-like">
              <i class="fa fa-heart" aria-hidden="true"></i>
              {{ presentation.likes }}
            </div>
            <div class="warp-list-views">
              <i class="fa fa-eye" aria-hidden="true"></i>
              {{ presentation.views }}
            </div>
          </div>
          <div class="presentation-info">
            <div class="presentation-title">{{ presentation.subject | truncatechars:23 }}</div>
            <div class="presentation-author">
              By <a class="author">{{ presentation.author }}</a>
            </div>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>

  <ul class="pagination text-center" role="navigation" aria-label="Pagination">
    {% if page_obj.has_previous %}
      <li class="pagination-previous">
        <a href="?{{ page_obj.previous_page_number.querystring }}">Previous</a>
      </li>
    {% else %}
    {% endif %}
    {% for page in page_obj.pages %}
      {% if page %}
        {% ifequal page page_obj.number %}
          <li class="current">{{ page }}</li>
        {% else %}
          <li><a href="?{{ page.querystring }}" aria-label="Page {{ page }}">{{ page }}</a></li>
        {% endifequal %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="pagination-next"><a href="?{{ page_obj.next_page_number.querystring }}" aria-label="Next page">Next</a></li>
    {% else %}
    {% endif %}
  </ul>
</div>

warp/templates/presentation/markdown_usage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{% block head_title %}Markdown Usage - warp{% endblock head_title %}{% endblock title %}

{% block content %}
<div id="markdown-usage" class="row">
  <div class="markdown-pane columns medium-12">
    <h2>Table of Contents</h3>
    <ul class="table-of-contents">
      <li><a href="#">Text</a></li>
      <li><a href="#">Lists</a></li>
      <li><a href="#">Images</a></li>
      <li><a href="#">Headers &amp; Quotes</a></li>
      <li><a href="#">Code</a></li>
      <li><a href="#">Extras</a></li>
    </ul>


      <div class="syntax-block">
        <h3>Slides</h3>
        <div class="row">
          <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">Slide 1
=====
Slide 2
=====
...</code></pre>
          </div>
          <div class="preview-side columns medium-6">
            <div class="divide-slide-preview"><span>Slide 1</span></div>
            <div class="divide-slide-preview"><span>Slide 2</span></div>
          </div>
        </div>
      </div>


      <div class="syntax-block">
      <h3>Headers</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown"># This is an &lt;h1&gt; tag
## This is an &lt;h2&gt; tag
###### This is an &lt;h6&gt; tag</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <h1>This is an &lt;h1&gt; tag</h1>
          <h2>This is an &lt;h2&gt; tag</h2>
          <h6>This is and &lt;h6&gt; tag</h6>
        </div>
      </div>
    </div>

    <div class="syntax-block">
      <h3>Emphasis</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <i>This text will be italic</i><br>
          <i>This will also be italic</i><br>
          <b>This text will be bold</b><br>
          <b>This will also be bold</b><br>
          <em>You <strong>can</strong> combine them</em>
        </div>
      </div>
    </div>

    <div class="syntax-block">
      <h3>Lists</h3>

      <h4>Unordered</h4>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">* Item 1
* Item 2
  * Item 2a
  * Item 2b</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <ul>
            <li>Item 1</li>
            <li>Item 2</li>
            <ul>
              <li>Item 2a</li>
              <li>Item 2b</li>
            </ul>
          </ul>
        </div>
      </div>
    </div>

    <div class="syntax-block">
      <h4>Ordered</h4>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">1. Item 1
1. Item 2
1. Item 3
  1. Item 3a
  1. Item 3b</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <ol>
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
            <ol>
              <li>Item 3a</li>
              <li>Item 3b</li>
            </ol>
          </ol>
        </div>
      </div>

    </div>

    <div class="syntax-block">
      <h3>Images</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">![Present](/images/usage-example.jpeg)
Format: ![Alt Text](url)</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <img src="{% static 'images/usage-example.jpeg'%}" alt="Usage image">
        </div>
      </div>

    </div>

    <div class="syntax-block">
      <h3>Links</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">https://google.com - automatic!
[Google](https://google.com)</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <a href="https://google.com">Google</a>
        </div>
      </div>
    </div>

    <div class="syntax-block">
      <h3>Blockquotes</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">As Kanye West said:
&gt; We're living the future so
&gt; the present is our past.</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <p>As Kanye West said:</p>
          <blockquote>
<p>We're living the future so
the present is our past.</p>
</blockquote>
        </div>
      </div>
    </div>

    <div class="syntax-block">
      <h3>Inline code</h3>

      <div class="row">
        <div class="markdown-side columns medium-6">
          <pre class="highlight"><code class="language-markdown">I think you should use an
`&lt;addr&gt;` element here instead.</code></pre>
        </div>
        <div class="preview-side columns medium-6">
          <p>I think you should use an
            <code class="language-markdown">&lt;addr&gt;</code> element here instead.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block prism_css %}
  <link rel="stylesheet" href="{% static 'vendor/prism/okaidia.css' %}">
{% endblock %}

warp/templates/presentation/presentation_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'presentation:delete' object.pk %}">
  {% csrf_token %}
  Are you sure you want to delete "{{ object }}" ?
  <input type="submit" value="Submit" />
</form>
{% endblock %}

warp/templates/presentation/presentation_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
  <div class="row" id="detail">
    <div class="small-12 medium-8 large-8 small-centered medium-centered large-centered columns">
      <div id="normal-view">
        <div class="slide-pane">
          <div class="pane-header">
            <div>
              <button id="likeBtn" class="button btn-primary"
                      onclick="{% if user.is_authenticated %}likePresentation({{ presentation.pk }}){% else %}showPopup(){% endif %}">
                {% if is_user_liked %}<i class="fa fa-heart" aria-hidden="true"></i>{% else %}<i class="fa fa-heart-o" aria-hidden="true"></i>{% endif %}
              </button>
              {% if presentation.author == request.user %}
                <a class="button btn-primary" href="{% url "presentation:update" presentation.pk %}">Update</a>
              {% endif %}
              {% if presentation.author == request.user %}
                <a class="button" href="{% url "presentation:delete" presentation.pk %}">Delete</a>
              {% endif %}
            </div>
          </div>
          <div class="slides">
            {% for slide in presentation.slide_set.all %}
              <div class="slide">{{ slide.markdown }}</div>
            {% endfor %}
            <a id="prev-touch"></a>
            <a id="next-touch"></a>
          </div>
          <div class="controller">
            <div class="arrows">
              {% spaceless %}
                <a id="prev-btn"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
                <a id="next-btn"><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
              {% endspaceless %}
            </div>
            <div class="extra-commands">
              <a id="full-screen-btn"><i class="fa fa-arrows-alt" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="presentation-info">
        <div class="presentation-title">
          {{ presentation.subject }}
          <div class="warp-list-views">
            <i class="fa fa-eye" aria-hidden="true"></i>
            {{ presentation.views }}
            Likes: <span id="likeCount">{{ presentation.likes }}</span>
          </div>
        </div>
        By <div class="presentation-author">
        <a>{{ presentation.author }}</a>
      </div>
        <br>
        Published <div class="presentation-published-date">
        {{ presentation.created }}
      </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_javascript %}
  <script src="{% static 'vendor/marked/marked.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/resize-slides.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/mdElemsToHtmlElems.min.js' %}"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/screenfull.js/3.2.0/screenfull.min.js"></script>
  <script type="text/javascript" src="{% static 'dist/js/detail/index.min.js' %}"></script>
  <script>
    {% if user.is_authenticated %}
      const likePresentation = (pk) => {
        $.ajax({
          method: "PUT",
          url: "/like/" + pk
        }).done(function (data) {
          const likeCount = Number($('#likeCount').text());
          const likeBtn = $('#likeBtn');
          if(data === 'True') {
            $('#likeCount').text(likeCount + 1);
            $('.fa-heart-o').removeClass('fa-heart-o').addClass('fa-heart');
          }
          else {
            $('#likeCount').text(likeCount - 1);
            $('.fa-heart').removeClass('fa-heart').addClass('fa-heart-o');
          }
        }).fail(function () {
        })
      };
    {% else %}
      const showPopup = () => {
        if(confirm('Like must be logged in. Go to sign-in page?')) {
          location.replace('{% url 'account_login' %}?next=/detail/{{ presentation.id }}');
        }
      };
    {% endif %}
  </script>
{% endblock %}

warp/templates/presentation/presentation_form.html
{% extends 'base.html' %}
{% load staticfiles crispy_forms_tags %}
{% block title %}{% block head_title %}Create Presentation - warp{% endblock head_title %}{% endblock title %}

{% block header %}
  <div class="form-header hide-for-small-only">
    <div class="small-11 small-centered medium-10 medium-centered large-10 large-centered columns">
      <div class="title">
        <a href="/">Warp</a>
      </div>
      <div class="feature small-offset-10 medium-offset-10 large-offset-11">
        <button class="publised-button" type="button" data-toggle="example-dropdown">Published <i class="fa fa-caret-down" aria-hidden="true"></i></button>
        <div class="dropdown-pane" id="example-dropdown" data-dropdown data-auto-focus="true">
          <div class="row contents-option">
            <span class="custom-label">Publishing scope</span>
            <div class="medium-12 columns switch-wrapper">
              <input type="radio" value="True" class="left-switch" name="is_public" id="{{ form.is_public.auto_id }}" checked/>
              <label for="{{ form.is_public.auto_id }}">Public</label>
              <input type="radio" value="False" class="right-switch" name="is_public" id="right-switch"/><label
                    for="right-switch">Private</label>
            </div>
          </div>
          <div class="row contents-header">
            <div class="small-12 medium-12 large-12 columns">
              <span class="custom-label">Subject*</span>
              <div class="input-group">
                <input type="text" class="input-group-field" maxlength="50" id="id_subject" name="subject" {% if form.subject.value %}value="{{ form.subject.value }}"{% endif %}>
                {% if form.subject.errors %}
                  <span class="form-error" data-form-error-for="id_subject" style="display: inline;">
                    {% for error in form.subject.errors %}
                      {{ error }}
                    {% endfor %}
                  </span>
                {% endif %}
              </div>
              <span class="custom-label">Add tags</span>
              <p>Add tags your presentation reaches more people (These are separated by <span class="emphasis">commas</span>.)</p>
              <div class="input-group">
                {{ form.tags }}
                {% if form.tags.errors %}
                  <span class="form-error" data-form-error-for="id_tags" style="display: inline;">
                      {% for error in form.tags.errors %}
                        {{ error }}
                      {% endfor %}
                    </span>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="medium-6 columns option option-wrapper">
            <button class="button" onclick="publish();">publish</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <style type="text/css">
    body {
      overflow-y: hidden;
    }
  </style>
  <form id="form_html" name="form" action="{{ action_url }}" method="post" data-abide>
    <div id="small-contents" class="show-for-small-only">
      <div class="callout callout-full text-center">
        <div>
          <h1>Sorry, we don't support this page on mobile devices.</h1>
          <h2>
            <a href="{% url 'presentation:list' %}"><strong>Go to main</strong></a>
          </h2>
        </div>
      </div>
    </div>
    <div id="large-medium-contents" class="hide-for-small-only medium-10 medium-centered large-10 large-centered">
      <div class="row contents-body">
        <div class="editor-side small-6 medium-6 large-6 columns">
          {% csrf_token %}
          {{ form.markdown }}
          <input type="hidden" id="exist_markdown" name="exist_markdown" {% if markdown %} value="{{ markdown }}"{% endif %} >
          <div id="markdown_editor"></div>
          <a class="usage-toggle-btn" href="{% url 'presentation:markdown-usage' %}" target="_blank"><i class="fa fa-question-circle" aria-hidden="true"></i></a>
        </div>
        <div class="preview-side small-6 medium-6 large-6 columns">
          <div class="preview">
            <div class="callout secondary slide data-slide-0"></div>
          </div>
        </div>
      </div>
    </div>
    {% if object.pk %}
      <input type="text" value="{{ object.pk }}" id="{{ form.pk.auto_id }}">
    {% endif %}
  </form>
{% endblock %}

{% block extra_javascript %}
  <script src="{% static 'vendor/marked/marked.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/form/preview.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/resize-slides.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'dist/js/form/index.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendor/ace/ace.js' %}"></script>
{% endblock %}