config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    # Your stuff: custom urls includes go here
    url(r'^', include('presentation.urls', namespace='presentation')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('warp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

presentation/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.PresentationList.as_view(),
        name='list'
    ),
    url(
        regex=r'^search$',
        view=views.PresentationSearchList.as_view(),
        name='search'
    ),
    url(
        regex=r'^create$',
        view=views.PresentationCreate.as_view(),
        name='create'
    ),
    url(
        regex=r'^markdown-usage$',
        view=views.presentation_markdown_usage,
        name='markdown-usage'
    ),
    url(
        regex=r'^detail/(?P<pk>\d+)$',
        view=views.PresentationDetail.as_view(),
        name='detail'
    ),
    url(
        regex=r'^update/(?P<pk>\d+)$',
        view=views.PresentationUpdate.as_view(),
        name='update'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)$',
        view=views.PresentationDelete.as_view(),
        name='delete'
    ),
    url(
        regex=r'^like/(?P<pk>\d+)$',
        view=views.like_presentation,
        name='like'
    ),
]

warp/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

warp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_profile_image_url(self):
        social_image = None
        if self.socialaccount_set.all():
            social_image = self.socialaccount_set.all()[0].get_avatar_url()
        if social_image:
            return social_image
        return '/static/images/default_profile.svg'

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

warp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from presentation.models import Presentation
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        if username == self.request.user.username:
            context['presentations'] = Presentation.objects.authored_by(username).order_by('-pk')[:9]
        else:
            context['presentations'] = Presentation.objects.authored_by(username).public().order_by('-pk')[:9]

        # TODO implement like presentation
        # context['like_presentation_list'] =

        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

warp/templates/components/footer.html
{% load i18n %}

<footer id="footer">
  <div class="small-10 small-centered">
    <div class="copyright">Copyright © 2017 <a href="https://github.com/SaturDJang" target="_blank">SaturDjang</a> Inc.</div>
    <div class="links">
      <a href="https://github.com/SaturDJang/warp" target="_blank">Github</a>
      <a href="mailto:saturdjang@gmail.com">Contact Us</a>
    </div>
  </div>
</footer>

warp/templates/components/header.html
{% load i18n %}

<div id="header" class="row">
  <div class="small-11 small-centered large-10 large-centered columns">
    <form action="{% url 'presentation:search' %}" method="get">
      <div class="title">
        <a href="/">Warp</a>
        <i class="fa fa-search" aria-hidden="true"></i>
        <input class="search" placeholder="search.." name="query" id="query" />
      </div>
    </form>
    <div class="feature">
      {% if user.is_authenticated %}
        <span class="name-warpper">Hi,<a href="{% url 'users:detail' request.user.username %}"><span
          class="user-name">{{ request.user.username }}</span></a></span>
        <div class="vertical-divider"></div>
        <a class="create-button" href="{% url 'presentation:create' %}">Create</a>
        <form method="post" action="{% url 'account_logout' %}">
          {% csrf_token %}
          {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
          {% endif %}
          <button class="btn btn-danger" type="submit">{% trans 'Sign Out' %}</button>
        </form>
      {% else %}
        <a href="{% url 'account_login' %}">Sign In?</a>
      {% endif %}
    </div>
  </div>
</div>